name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk wget
          pip install buildozer cython virtualenv

      - name: Install Android SDK and NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          mkdir -p android-sdk/cmdline-tools
          unzip tools.zip -d android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.2.9519653" "cmake;3.22.1"
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          PATH: $PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=$ANDROIDSDK/ndk/25.2.9519653
          export PATH=$PATH:$ANDROIDSDK/platform-tools:$ANDROIDNDK
          buildozer -v android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          PATH: $PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodificadorApp
          path: bin/*.apk
